---
    - apt: "name={{ item }} state=installed"
      with_items:
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-geoip
        - php5-gmp
        - php5-imagick
        - php5-intl
        - php5-mcrypt
        - php5-memcache
        - php5-mysql
        - php5-xcache
        - php5-xdebug
        - php5-xhprof
        - php5-dev
        - php-pear
        - libyaml-dev
    - template: src=templates/php/php.ini.j2 dest=/etc/php5/cli/php.ini owner=root group=root mode=0644
    - name: Install PHP Yaml package from PECL
      shell: "(php -m | grep yaml) || (yes '' | pecl install yaml)"
    - command: php5enmod yaml
